// <auto-generated />
using System;
using AssetManagementApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetManagementApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250818071142_FinalSchemaFix")]
    partial class FinalSchemaFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssetManagementApi.Models.Asset", b =>
                {
                    b.Property<string>("TagNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AreaCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AssetType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("CMMMSRequired")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeckPlatform")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FacilitySection")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FunctionalClassID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("InstallationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastMaintenance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Site")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subsystem")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("System")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TagFormatID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValidationStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TagNumber");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("AssetManagementApi.Models.Asset2DModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetTagNumber")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AssetTagNumber1")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssetTagNumber");

                    b.HasIndex("AssetTagNumber1");

                    b.ToTable("Asset2DModels");
                });

            modelBuilder.Entity("AssetManagementApi.Models.Asset3DModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagNumber")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TagNumber");

                    b.ToTable("Asset3DModels");
                });

            modelBuilder.Entity("AssetManagementApi.Models.AssetDocuments", b =>
                {
                    b.Property<string>("TagNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssetTagNumber")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagNumber");

                    b.HasIndex("AssetTagNumber");

                    b.ToTable("AssetDocuments");
                });

            modelBuilder.Entity("AssetManagementApi.Models.AssetRelationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetTagNumber")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AssociatedTagNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryTagNumber")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RelationshipType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssetTagNumber");

                    b.HasIndex("PrimaryTagNumber");

                    b.ToTable("AssetRelationships");
                });

            modelBuilder.Entity("AssetManagementApi.Models.Asset2DModels", b =>
                {
                    b.HasOne("AssetManagementApi.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetTagNumber");

                    b.HasOne("AssetManagementApi.Models.Asset", null)
                        .WithMany("Asset2DModels")
                        .HasForeignKey("AssetTagNumber1");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("AssetManagementApi.Models.Asset3DModels", b =>
                {
                    b.HasOne("AssetManagementApi.Models.Asset", "Asset")
                        .WithMany("Asset3DModels")
                        .HasForeignKey("TagNumber");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("AssetManagementApi.Models.AssetDocuments", b =>
                {
                    b.HasOne("AssetManagementApi.Models.Asset", "Asset")
                        .WithMany("AssetDocuments")
                        .HasForeignKey("AssetTagNumber");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("AssetManagementApi.Models.AssetRelationship", b =>
                {
                    b.HasOne("AssetManagementApi.Models.Asset", null)
                        .WithMany("AssetRelationships")
                        .HasForeignKey("AssetTagNumber");

                    b.HasOne("AssetManagementApi.Models.Asset", "PrimaryAsset")
                        .WithMany()
                        .HasForeignKey("PrimaryTagNumber");

                    b.Navigation("PrimaryAsset");
                });

            modelBuilder.Entity("AssetManagementApi.Models.Asset", b =>
                {
                    b.Navigation("Asset2DModels");

                    b.Navigation("Asset3DModels");

                    b.Navigation("AssetDocuments");

                    b.Navigation("AssetRelationships");
                });
#pragma warning restore 612, 618
        }
    }
}
